In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv("./wisc_bc_data.csv", encoding="utf-8")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0     87139402         B        12.32         12.39           78.85   
1      8910251         B        10.60         18.95           69.28   
2       905520         B        11.04         16.83           70.92   
3       868871         B        11.28         13.39           73.00   
4      9012568         B        15.19         13.21           97.65   
..         ...       ...          ...           ...             ...   
564  911320502         B        13.17         18.22           84.28   
565     898677         B        10.26         14.71           66.20   
566     873885         M        15.28         22.41           98.92   
567     911201         B        14.53         13.98           93.86   
568    9012795         M        21.37         15.10          141.30   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0        464.1          0.10280           0.06981         0.03987   
1        346.4          0.09688           0.11470         0.06387   
2        373.2          0.10770           0.07804         0.03046   
3        384.8          0.11640           0.11360         0.04635   
4        711.8          0.07963           0.06934         0.03393   
..         ...              ...               ...             ...   
564      537.3          0.07466           0.05994         0.04859   
565      321.6          0.09882           0.09159         0.03581   
566      710.6          0.09057           0.10520         0.05375   
567      644.2          0.10990           0.09242         0.06895   
568     1386.0          0.10010           0.15150         0.19320   

     points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0        0.03700  ...         13.50          15.64            86.97   
1        0.02642  ...         11.88          22.94            78.28   
2        0.02480  ...         12.41          26.44            79.93   
3        0.04796  ...         11.92          15.77            76.53   
4        0.02657  ...         16.20          15.73           104.50   
..           ...  ...           ...            ...              ...   
564      0.02870  ...         14.90          23.89            95.10   
565      0.02037  ...         10.88          19.48            70.89   
566      0.03263  ...         17.80          28.03           113.80   
567      0.06495  ...         15.80          16.93           103.10   
568      0.12550  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.08488  
566       0.12260          0.3175          0.09772  
567       0.10690          0.2606          0.07810  
568       0.19660

* diagnosis = y값 -> 암인지 아닌지 분류 (즉, 이진 분류에 해당)
* 나머지 변수들 = x값(특성)

In [75]:
# 결측치는 존재하지 않음!!
df.isnull().sum()

id                   0
diagnosis            0
radius_mean          0
texture_mean         0
perimeter_mean       0
area_mean            0
smoothness_mean      0
compactness_mean     0
concavity_mean       0
points_mean          0
symmetry_mean        0
dimension_mean       0
radius_se            0
texture_se           0
perimeter_se         0
area_se              0
smoothness_se        0
compactness_se       0
concavity_se         0
points_se            0
symmetry_se          0
dimension_se         0
radius_worst         0
texture_worst        0
perimeter_worst      0
area_worst           0
smoothness_worst     0
compactness_worst    0
concavity_worst      0
points_worst         0
symmetry_worst       0
dimension_worst      0
dtype: int64

accurancy로 평가하면, 판단을 어떻게 하느냐에따라 결과가 변경되는 문제가 발생한다.
confusion matrix(혼돈 행렬) 라는 개념을 가지고 와서 어떤 때는 precision을 보고, 어떤 때는 recall값을 보는지 확인 할 것이다.

In [76]:
# 총 데이터 개수는 569개
len(df)

569

In [77]:
# 총 column 개수는 32개
len(df.columns)

32

In [78]:
# 환자 식별 번호가 필요할까?
# B = 양성, M = 악성
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [79]:
# 일단 y값을 encoder를 통해 0과 1 값으로 바꿔줘야할 것 같다..
# 즉, y값이 머신러닝이 학습할 수 있도록 LabelEncoding 해주기
from sklearn.preprocessing import LabelEncoder

In [80]:
encoder = LabelEncoder()
encoder.fit(df['diagnosis'])

df['diagnosis'] = encoder.transform(df['diagnosis'])

In [81]:
# 0 = 양성, M = 악성
df['diagnosis'].value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

In [82]:
# id는 딱히 필요할 것 같지 않아서.. 삭제
df.drop(['id'],axis=1, inplace=True)

In [83]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            0        12.32         12.39           78.85      464.1   
1            0        10.60         18.95           69.28      346.4   
2            0        11.04         16.83           70.92      373.2   
3            0        11.28         13.39           73.00      384.8   
4            0        15.19         13.21           97.65      711.8   
..         ...          ...           ...             ...        ...   
564          0        13.17         18.22           84.28      537.3   
565          0        10.26         14.71           66.20      321.6   
566          1        15.28         22.41           98.92      710.6   
567          0        14.53         13.98           93.86      644.2   
568          1        21.37         15.10          141.30     1386.0   

     smoothness_mean  compactness_mean  concavity_mean  points_mean  \
0            0.10280           0.06981         0.03987      0.03700   
1            0.09688           0.11470         0.06387      0.02642   
2            0.10770           0.07804         0.03046      0.02480   
3            0.11640           0.11360         0.04635      0.04796   
4            0.07963           0.06934         0.03393      0.02657   
..               ...               ...             ...          ...   
564          0.07466           0.05994         0.04859      0.02870   
565          0.09882           0.09159         0.03581      0.02037   
566          0.09057           0.10520         0.05375      0.03263   
567          0.10990           0.09242         0.06895      0.06495   
568          0.10010           0.15150         0.19320      0.12550   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.1959  ...         13.50          15.64            86.97   
1           0.1922  ...         11.88          22.94            78.28   
2           0.1714  ...         12.41          26.44            79.93   
3           0.1771  ...         11.92          15.77            76.53   
4           0.1721  ...         16.20          15.73           104.50   
..             ...  ...           ...            ...              ...   
564         0.1454  ...         14.90          23.89            95.10   
565         0.1633  ...         10.88          19.48            70.89   
566         0.1727  ...         17.80          28.03           113.80   
567         0.1650  ...         15.80          16.93           103.10   
568         0.1973  ...         22.69          21.84           152.10   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0         549.1            0.1385             0.1266          0.12420   
1         424.8            0.1213             0.2515          0.19160   
2         471.4            0.1369             0.1482          0.10670   
3         434.0            0.1367             0.1822          0.08669   
4         819.1            0.1126             0.1737          0.13620   
..          ...               ...                ...              ...   
564       687.6            0.1282             0.1965          0.18760   
565       357.1            0.1360             0.1636          0.07162   
566       973.1            0.1301             0.3299          0.36300   
567       749.9            0.1347             0.1478          0.13730   
568      1535.0            0.1192             0.2840          0.40240   

     points_worst  symmetry_worst  dimension_worst  
0         0.09391          0.2827          0.06771  
1         0.07926          0.2940          0.07587  
2         0.07431          0.2998          0.07881  
3         0.08611          0.2102          0.06784  
4         0.08178          0.2487          0.06766  
..            ...             ...              ...  
564       0.10450          0.2235          0.06925  
565       0.04074          0.2434          0.08488  
566       0.12260          0.3175          0.09772  
567

## 타이타닉 따라해봄 _20220425_오전3

In [84]:
import matplotlib.pyplot as plt
import seaborn as sns

In [85]:
df.head(5)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        12.32         12.39           78.85      464.1   
1          0        10.60         18.95           69.28      346.4   
2          0        11.04         16.83           70.92      373.2   
3          0        11.28         13.39           73.00      384.8   
4          0        15.19         13.21           97.65      711.8   

   smoothness_mean  compactness_mean  concavity_mean  points_mean  \
0          0.10280           0.06981         0.03987      0.03700   
1          0.09688           0.11470         0.06387      0.02642   
2          0.10770           0.07804         0.03046      0.02480   
3          0.11640           0.11360         0.04635      0.04796   
4          0.07963           0.06934         0.03393      0.02657   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.1959  ...         13.50          15.64            86.97   
1         0.1922  ...         11.88          22.94            78.28   
2         0.1714  ...         12.41          26.44            79.93   
3         0.1771  ...         11.92          15.77            76.53   
4         0.1721  ...         16.20          15.73           104.50   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0       549.1            0.1385             0.1266          0.12420   
1       424.8            0.1213             0.2515          0.19160   
2       471.4            0.1369             0.1482          0.10670   
3       434.0            0.1367             0.1822          0.08669   
4       819.1            0.1126             0.1737          0.13620   

   points_worst  symmetry_worst  dimension_worst  
0       0.09391          0.2827          0.06771  
1       0.07926          0.2940          0.07587  
2       0.07431          0.2998          0.07881  
3       0.08611          0.2102          0.06784  
4       0.08178          0.2487          0.06766  

[5 rows x 31 columns]

In [86]:
# x값(특성값)은 id를 제외하고는 모두 유의미해보였기 때문에 diagnosis, id만 제거
# y값 = 예측해야할 값 = 유방암인지 아닌지 예측 = diagnosis 
y_df = df['diagnosis']

X_df = df.drop(['diagnosis'],axis=1)

In [87]:
# 데이터를 적절히 섞어주기 위해 train_test_split 사용하기
from sklearn.model_selection import train_test_split

In [88]:
# 훈련 데이터와 테스트 데이터를 적절하게 만들어주기 위해 train_test_split 사용
# 전체 데이터에서 0.2 = 20%를 test 데이터로 만듦
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size =0.2, random_state =11)

# LogisticRegression 사용하여 학습시키기

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [90]:
# 로지스틱 회귀 객체 생성
lr = LogisticRegression(max_iter =1000)

# 훈련시키기
lr.fit(X_train, y_train)

# 테스트 세트 y값 예측하기
lr_pred = lr.predict(X_test)

C:\Users\wlswn\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [91]:
# 얼마나 정확하게 맞췄는지 점수로 환산
# y_test = 정답, lr_pred = 모델이 예측한 값을 비교한 듯 싶음
print(accuracy_score(y_test, lr_pred))

0.9385964912280702


In [72]:
# y값 분포 확인하기
y_test.value_counts()

0    67
1    47
Name: diagnosis, dtype: int64

---

## 스케일링 한뒤 학습하기? - 20220425_오전1 참고

In [46]:
from sklearn.preprocessing import StandardScaler

In [48]:
ss = StandardScaler()

ss.fit(X_train)

train_scaled = ss.transform(X_train)
test_scaled = ss.transform(X_test)

In [49]:
# knn
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, y_train)

print(kn.score(train_scaled, y_train))
print(kn.score(test_scaled, y_test))

0.9802197802197802
0.9736842105263158


In [50]:
print(kn.classes_)

[0 1]


In [51]:
import numpy as np

proba = kn.predict_proba(test_scaled[:5])
# decimal은 소수점 이하 자리수를 의미 
print(np.round(proba, decimals=4))

# 첫번째 = Perch 일 확률 100%, 두번째 = Smelt일 확률 100%...~
# 4번 째 = Perch일 확률 0.6667 , 0.3333보다 값이 크기 때문에 Perch라고 판단함

[[1.     0.    ]
 [1.     0.    ]
 [0.3333 0.6667]
 [0.     1.    ]
 [1.     0.    ]]


--- 

knn이 한계가 있어서 로지스틱 회귀를 사용한다고 했다 ..!

In [54]:
# 로지스틱 회귀로 이진 분류 수행하기
# 여기서는 어차피 이진 분류이기 때문에 불리언 인덱싱을 사용하지 않아도 될듯?
# 일단 StandardScaler의 역할이 정확하게 뭔지는 모르겠는데....
# 데이터 세트를 섞은 후, 표준화 시킨 것 = train_scaled, test_scaled
train_scaled

array([[-0.86363747, -0.56009448, -0.85434083, ..., -0.59584121,
         0.16062733, -0.2634876 ],
       [ 0.81482654,  0.04068093,  0.72023921, ..., -0.44205929,
        -0.57612416, -1.28771678],
       [-0.14305551, -1.90555728, -0.14057042, ..., -0.59951361,
        -0.28987039, -0.63369092],
       ...,
       [-1.44560146, -0.44587863, -1.36393677, ...,  0.94488532,
         2.08462802,  1.81233362],
       [-0.44980928, -0.45044726, -0.45397403, ..., -0.12164203,
         0.21850377, -0.38152344],
       [ 0.27366659, -0.53268268,  0.20854271, ..., -0.43456146,
        -0.76852423, -1.04306068]])

In [55]:
test_scaled

array([[-0.16331283, -0.12150559, -0.16031569, ...,  0.45064094,
         0.974026  ,  0.15714922],
       [-0.04466279, -0.70172215, -0.11494359, ..., -0.88274778,
        -0.83422181, -0.67553999],
       [-0.15752502,  0.35134806, -0.11998493, ...,  1.72221086,
        -0.13814026,  1.25434601],
       ...,
       [ 2.67560648,  0.63003475,  2.55612895, ...,  1.85686567,
         1.0850862 ,  0.43721608],
       [ 0.26787879, -0.11693696,  0.27660086, ..., -0.44680281,
        -0.06774999,  0.4538484 ],
       [-0.50768734, -0.31110391, -0.53967689, ..., -0.27435283,
         0.87547962, -0.79196625]])

### LogisticRegression 클래스

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
# LogisticRegression 클래스 객체 생성 
lr = LogisticRegression()

# train_scaled, y_train(정답) 값 훈련시키기
lr.fit(train_scaled, y_train)

LogisticRegression()

In [58]:
# 0 = 양성, M = 악성 
# 5명이 모두 양성
lr.predict(train_scaled[:5])

array([0, 0, 0, 0, 0])

In [59]:
# 양성인지 악성인지만 확인하면 되기 때문에 0과 1로 나오는게 맞다!
print(lr.classes_)

[0 1]


### 시그모이드 함수 사용해볼까 ㅎ;

In [60]:
lr.coef_

array([[ 0.30262125,  0.35306775,  0.29690477,  0.36094165,  0.30237341,
        -0.46731147,  0.75583737,  0.9019393 , -0.18897672, -0.32776365,
         1.23456902, -0.20930881,  0.59103654,  0.97794824,  0.14801729,
        -0.61640286, -0.07902555,  0.29443655, -0.33930577, -0.50384698,
         0.90951968,  1.42078517,  0.75012091,  0.89443527,  0.54255782,
        -0.0403362 ,  0.58799859,  0.85504451,  0.94325177,  0.46477945]])

In [62]:
# z값을 출력하기 위해 decision_function() 메서드 사용
decisions = lr.decision_function(train_scaled[:5])

# 처음 5개 데이터에 대한 z값은?
print(decisions)

[-5.94197457 -0.6859158  -6.98990348 -4.82889684 -7.34993188]


In [63]:
# numpy와 scipy는 대부분 같이 사용한다!
from scipy.special import expit

# decisions = z값, expit(decisions) = 로지스틱 회귀??
# 0.5를 기준으로 아래이면 0, 위이면 1에 해당한다.
print(expit(decisions))

[0.00261996 0.33494224 0.00092029 0.00793192 0.00064222]


In [65]:
# 모두 z값이 0.5 이하이므로 0이라 예측한다(양성)
lr.predict(train_scaled[:5])

array([0, 0, 0, 0, 0])