In [1]:
from tensorflow import keras

In [2]:
def model_fn(a_layer=None):
    model = keras.Sequential()
    model.add(keras.layers.Flatten(input_shape=(28, 28)))
    model.add(keras.layers.Dense(100, activation='relu'))
    if a_layer:
        model.add(a_layer)
    model.add(keras.layers.Dense(10, activation='softmax'))
    return model

In [3]:
model = model_fn(keras.layers.Dropout(0.3))

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 100)               78500     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1010      
                                                                 
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(784, 100) dtype=float32, numpy=
 array([[ 0.00458717,  0.04122329,  0.08134137, ...,  0.03641072,
         -0.04021905, -0.08194385],
        [-0.08127993,  0.07054527, -0.0171392 , ..., -0.08018257,
          0.00874113, -0.05341079],
        [ 0.07897978, -0.07494382,  0.07344522, ...,  0.03376877,
         -0.04241084,  0.06053679],
        ...,
        [-0.08175341, -0.03180736, -0.06720321, ..., -0.01573103,
         -0.03269764,  0.06327191],
        [-0.04183774,  0.08060695,  0.03395859, ...,  0.0793599 ,
          0.01784056, -0.06369404],
        [-0.023242  , -0.07934999, -0.02946256, ...,  0.05191804,
          0.04984112, -0.054942  ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(100,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [7]:
model.load_weights("model-weights.h5")

In [8]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(784, 100) dtype=float32, numpy=
 array([[-0.21164152,  0.06394979, -0.05460935, ..., -0.3459981 ,
         -0.01771959,  0.29313168],
        [-0.10996902,  0.23640251, -0.13492274, ...,  0.31682172,
          0.13777716,  0.25216168],
        [ 0.18679287,  0.23523515,  0.20174745, ..., -0.13180284,
          0.04841439,  0.19995193],
        ...,
        [-0.10764236, -0.21010779, -0.01686038, ...,  0.00241488,
          0.16516492,  0.24610503],
        [ 0.4052784 ,  0.47000206,  0.11660096, ..., -0.13485998,
          0.14037384,  0.29945546],
        [ 0.22808516,  0.23333326,  0.20032492, ..., -0.45342848,
          0.3505349 ,  0.3471044 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(100,) dtype=float32, numpy=
 array([-0.4773707 , -0.33014464, -0.04646168, -0.4786999 , -0.74623233,
         0.01731915,  0.05956275,  0.19477248,  0.26018426,  0.5979957 ,
         1.1837978 ,  0.17599978, -0.08054913,  0.35926324, -0.33847296,
    

In [10]:
model2 = keras.models.load_model("./model-whole.h5")

In [11]:
model2.weights

[<tf.Variable 'dense_8/kernel:0' shape=(784, 100) dtype=float32, numpy=
 array([[-0.21164152,  0.06394979, -0.05460935, ..., -0.3459981 ,
         -0.01771959,  0.29313168],
        [-0.10996902,  0.23640251, -0.13492274, ...,  0.31682172,
          0.13777716,  0.25216168],
        [ 0.18679287,  0.23523515,  0.20174745, ..., -0.13180284,
          0.04841439,  0.19995193],
        ...,
        [-0.10764236, -0.21010779, -0.01686038, ...,  0.00241488,
          0.16516492,  0.24610503],
        [ 0.4052784 ,  0.47000206,  0.11660096, ..., -0.13485998,
          0.14037384,  0.29945546],
        [ 0.22808516,  0.23333326,  0.20032492, ..., -0.45342848,
          0.3505349 ,  0.3471044 ]], dtype=float32)>,
 <tf.Variable 'dense_8/bias:0' shape=(100,) dtype=float32, numpy=
 array([-0.4773707 , -0.33014464, -0.04646168, -0.4786999 , -0.74623233,
         0.01731915,  0.05956275,  0.19477248,  0.26018426,  0.5979957 ,
         1.1837978 ,  0.17599978, -0.08054913,  0.35926324, -0.33847296,
